[package]
name = "gm-export"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
imessage-database = "1.0.0"
rusqlite = "0.28.0"
serde = { version= "1.0.152", features = ["derive"]}

